// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: GetFeedByURL.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedByUrl = `-- name: GetFeedByUrl :one
SELECT id FROM feeds
WHERE url = $1
`

func (q *Queries) GetFeedByUrl(ctx context.Context, url string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getFeedByUrl, url)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
