// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: GetUserByName.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserByName = `-- name: GetUserByName :one
SELECT id FROM users
WHERE name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
