// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: names.sql

package database

import (
	"context"
)

const getName = `-- name: GetName :one


SELECT name from users
`

func (q *Queries) GetName(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getName)
	var name string
	err := row.Scan(&name)
	return name, err
}
